const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const crypto=require('node:crypto');
const home=os.homedir();
const config=path.join(home,'.config/opencode');
const dest=path.resolve(process.argv[2]||path.join(home,'Desktop/Auto D'));
if(fs.existsSync(dest))throw Error('Destination already exists; do not overwrite a release');
const cp=(src,rel)=>{const out=path.join(dest,rel);fs.mkdirSync(path.dirname(out),{recursive:true});fs.cpSync(src,out,{recursive:true,dereference:true});};
cp(path.resolve(__dirname,'..'),'skills/auto');
for(const name of ['stx','multi-image-generation'])cp(path.join(config,'skills',name),'skills/'+name);
cp(path.join(config,'plugins/fast-image.ts'),'image-runtime/plugins/fast-image.ts');
cp(path.join(config,'providers/direct-image-provider.js'),'image-runtime/providers/direct-image-provider.js');
cp(path.join(config,'fast-image.test.ts'),'image-runtime/fast-image.test.ts');
for(const name of ['st.md','stx.md','分集.md','分镜.md'])cp(path.join(config,'command',name),'commands/'+name);
cp(path.join(config,'agents/image-fast.md'),'agents/image-fast.md');
cp(path.join(config,'AGENTS.md'),'user-preferences.md');
cp('C:/Program Files/nodejs/node.exe','runtimes/node.exe');
cp('C:/Program Files/nodejs/node_modules/npm','runtimes/node_modules/npm');
cp(path.join(home,'AppData/Roaming/npm/node_modules/bun/bin/bun.exe'),'runtimes/bun.exe');
cp(path.join(home,'.libtv/libtv.exe'),'runtimes/libtv.exe');
for(const name of ['install-auto-d.cjs','check-auto-d.cjs','probe-installed-plugin.mjs','diagnose-auto-host.cjs','host-config-evidence.cjs','test-host-config-evidence.cjs'])cp(path.join(__dirname,name),name);
const pkg={name:'auto-d-direct-image-runtime',private:true,type:'module',dependencies:{'@opencode-ai/plugin':'1.17.11',sharp:'0.35.4'}};
fs.writeFileSync(path.join(dest,'image-runtime/package.json'),JSON.stringify(pkg,null,2));
fs.writeFileSync(path.join(dest,'Install.cmd'),'@echo off\r\n"%~dp0runtimes\\node.exe" "%~dp0install-auto-d.cjs" %*\r\npause\r\n');
fs.writeFileSync(path.join(dest,'Check.cmd'),'@echo off\r\n"%~dp0runtimes\\node.exe" "%~dp0check-auto-d.cjs"\r\npause\r\n');
fs.writeFileSync(path.join(dest,'Diagnose.cmd'),'@echo off\r\n"%~dp0runtimes\\node.exe" "%~dp0diagnose-auto-host.cjs" %*\r\npause\r\n');
fs.writeFileSync(path.join(dest,'README.md'),'# Auto D\n\n完整Windows x64便携依赖包。运行Install.cmd安装到当前用户OpenCode，关闭并重启OpenCode，再确认direct_image_run存在。Check.cmd仅离线校验，不代表已配置API密钥或登录。\n\n包含Auto八个内置模块、全部资源、锁定依赖、图片工具插件与provider、stx和多图执行说明、命令、测试、Node/Bun及可选LibTV程序。不含用户密钥、登录态、模型或项目素材。现有被替换文件备份到目标目录auto-d-backups；不修改opencode.json。仅支持Windows x64。\n\n/分镜与/分集进入相同预视频工作流；TSC由Agent按内置模块编写，不需要独立分镜生成器。工具或真实输入缺失仍阻断对应阶段，禁止用临时API绕过。\n\nstx密钥使用IMAGE_API_STX_KEY或桌面gaisc.json（base_url=https://grsai.dakka.com.cn，model=gpt-image-2），不在本包中。其他路线使用IMAGE_API_ST1_KEY等环境变量。原始宣传物料必须实际出现在场景和道具中，文本和入画需人工核验。\n\n未来发布同样必须包含所有工具、技能资源、固定依赖和就绪检查。用户指定SEG为最大单位时保留该粒度，不制作交付预览。\n\n版本：Auto规则1.8.4 + Auto D修订；Node 24.16.0，Bun 1.3.14，LibTV 1.1.3。LibTV为用户现有官方二进制，仅复制以便个人设备迁移，继续遵守官方服务条款，接收机器独立登录。运行时第三方包许可证保留在各node_modules中。\n');
console.log(JSON.stringify({dest,next:'Install pinned image-runtime dependencies, then seal manifest and run check'},null,2));
